# Generated by Django 5.2 on 2025-04-14 16:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSentimentScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_id', models.UUIDField()),
                ('total_mentions', models.IntegerField()),
                ('email_count_analyzed', models.IntegerField()),
                ('positive_mentions', models.IntegerField()),
                ('neutral_mentions', models.IntegerField()),
                ('negative_mentions', models.IntegerField()),
                ('management_complaints', models.IntegerField()),
                ('pay_complaints', models.IntegerField()),
                ('harassment_concerns', models.IntegerField()),
                ('positive_score', models.FloatField()),
                ('negative_score', models.FloatField()),
                ('overall_sentiment_score', models.FloatField()),
                ('trend_score', models.FloatField()),
                ('analysis_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remark', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
