# Generated by Django 5.2 on 2025-04-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_sentiment_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesentimentscore',
            name='text',
            field=models.TextField(default='No data'),
        ),
        migrations.AlterField(
            model_name='employeesentimentscore',
            name='employee_id',
            field=models.CharField(max_length=100),
        ),
    ]
